package az.zero.azpokedex.utils

const val SCREEN_POKEMON_LIST = "POKEMON_LIST_SCREEN"
const val SCREEN_POKEMON_DETAILS = "SCREEN_POKEMON_DETAILS"

const val ARGS_DOMINANT_COLOR = "ARGS_DOMINANT_COLOR"
const val ARGS_POKEMON_NAME = "ARGS_POKEMON_NAME"

const val PAGE_SIZE = 20